language: node_js
node_js:
- 10.6.0
os:
- linux
env:
- NODE_ENV=test
script:
- npm test
branches:
  only:
  - master
install:
- npm install
notifications:
  email:
    recipients:
    - kris17demon@gmail.com
    on_success: never
    on_failure: change
deploy:
  api_key:
    secure: aa3NKVT3VpXaowVw3MHULDja9XAWVFqWgk/yAQrjpSlzggStOVRCp5LX4+alZSt6vhfAKS2/GMx26YBNwe0b+8jQ5yen8PVtmOGquoXR9MNBm1ReiTU5LTZe6dAa12NMtgT1jx1H/d4rtqSVAbsgSHkvUq89tupWDy2WSHW79JoX+KD9L6rWpLO6+fnBu73kFXjxclEG3C5PrAO60ZKJYEbeslrIdihCxJW5A/5MythOKNONSngOX7EAVle9DPXVRonjvnDoe4NYreHI6ZU5HbYYuBVfSeFSDvGHiy0HOW4EH5kV7dyEdpru2f9OMC7+PuFx8r9tdxl7Ff/vdEO3J6VxcxyKX7nCTR52jUGm7kZfq+tWc54JzTgqiLjFtEL6zUu6US0D0VDyBV8mW0iSCKDk7GCNvle5hlLL/nq/bsxAb87qZuZLq5QaVA+zqVd5qnW2aIfRh7YkhKTEKLfIxhMwCwEDmaUc5gQRlssAFNtrjE/UP4RCR369D/wSSco4sRcIGCaQGf2XSHTiVRytmSKswMcVk/Q3CxKKyXVSWFIeiSeiS4Khj4+MAKrG0MJZAHiovUxp9Bn42rCePqLLJEoKoCQiwmA9wLQCC/iRVV9kFCSKoHnst/sHTIgeDnXF5zw3nnF0NN4L1ehIpoaQ1ew2NkmI3cSb2YEcyYSRQXY=
  app: sai-chat